name: test-if
on: 
  push:
    branches:
      - main
      - test
jobs:
  test-if:
    runs-on: ubuntu-latest
    steps:
      - name: run if push to main
        if: github.actor == 'heamnth' || github.actor == 'ddevsec-blip'
        run: echo "pushed to main branch"
      - name: run noramally
        run: echo "this if normal run"
